# Generated by Django 6.0.3 on 2026-03-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_rename_created_orden_creado_seguimiento'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pago',
            new_name='Pagos',
        ),
        migrations.DeleteModel(
            name='Seguimiento',
        ),
    ]
