# Generated by Django 6.0.3 on 2026-03-24 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_rename_created_orden_creado_seguimiento'),
        ('pagos', '0002_rename_pago_pagos_delete_seguimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error')], default='pending', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('card', 'Tarjeta'), ('pse', 'PSE'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata')], max_length=20, null=True)),
                ('referencia', models.CharField(max_length=200, unique=True)),
                ('wompi_id', models.CharField(blank=True, max_length=200, null=True)),
                ('respuesta', models.JSONField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
    ]
