"""
Django settings for verdeEsmeralda project.
Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path

# ------------------------------------------------------------
# Rutas base del proyecto
# ------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------
# Configuración básica de seguridad
# ------------------------------------------------------------
DEBUG = True  # Cambiar a False en producción
ALLOWED_HOSTS = [
     "*"
    # "127.0.0.1",
    # "localhost",
    # "unstridulating-cloddily-adalberto.ngrok-free.dev"
]
SECRET_KEY = 'django-insecure-85%u$(k#ds9j%*51**9s@y$a1(t2un%x8taflzwf9bfyl#qcdw'

# ------------------------------------------------------------
# Aplicaciones instaladas
# ------------------------------------------------------------
INSTALLED_APPS = [

    "jazzmin",
    # Apps Django por defecto
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # obligatorio para allauth

    'django.contrib.humanize',

    #crispy form
    "crispy_forms",
    "crispy_bootstrap5",

    # Django Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # login con Google

    #ckeditor
    'ckeditor',
    "ckeditor_uploader",

    # "captcha",
  

    # Apps propias
    'core',
    'usuarios.apps.UsuariosConfig',
    'productos',
    'ordenes',
    # 'listaDeseos',
    'listaDeseos.apps.WishlistConfig', 
    'pagos',
    # 'carrito',
    'carrito.apps.CarritoConfig',
    'blog',
]



# ------------------------------------------------------------
# Forms
# ------------------------------------------------------------
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ------------------------------------------------------------
# Middleware
# ------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Middleware de allauth
    "allauth.account.middleware.AccountMiddleware",
]

# ------------------------------------------------------------
# Configuración de URLs y templates
# ------------------------------------------------------------
ROOT_URLCONF = 'verdeEsmeralda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # obligatorio para allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #para el carrito
                "carrito.context_processors.carrito_contador",
                #categorias
                'productos.context_processors.categorias',
                #wishlist
                "listaDeseos.context_processors.wishlist_contador",
#sitio
                "core.context_processors.config_sitio",
            ],
        },
    },
]

WSGI_APPLICATION = 'verdeEsmeralda.wsgi.application'

# ------------------------------------------------------------
# Base de datos (SQLite para desarrollo)
# ------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ------------------------------------------------------------
# Validación de contraseñas
# ------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------------------------------------------
# Internacionalización
# ------------------------------------------------------------
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------
# Archivos estáticos y media
# ------------------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "full",
        "height": 400,
        "width": "100%",
        "extraPlugins": "uploadimage,image2",
        "removePlugins": "stylesheetparser",
    },
}
# ------------------------------------------------------------
# Configuración de Django Allauth
# ------------------------------------------------------------
# Django Allauth configuración
# ------------------------------------------------------------

# Allauth configuración limpia y sin CRITICAL ni warnings
SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

# Login con username o email
ACCOUNT_LOGIN_METHODS = {"username", "email"}

# Campos obligatorios en registro
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]

# Verificación de correo
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

# URLs de redirección
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# ------------------------------------------------------------
# Configuración de correo con Gmail (SMTP real)
# ------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "carlosforero2023@gmail.com"
EMAIL_HOST_PASSWORD = "ibaa bany ypoy moqc"  # contraseña de aplicación
DEFAULT_FROM_EMAIL = "Verde Esmeralda <carlosforero2023@gmail.com>"


ACCOUNT_LOGOUT_ON_GET = True
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ------------------------------------------------------------
# Configuración de correo con Gmail (SMTP real)
# ------------------------------------------------------------

from decouple import config

WOMPI_PUBLIC_KEY = config("WOMPI_PUBLIC_KEY").strip()
WOMPI_PRIVATE_KEY = config("WOMPI_PRIVATE_KEY").strip()
WOMPI_INTEGRITY_KEY = config("WOMPI_INTEGRITY_KEY").strip()

# 🔐 ESTE TE FALTA
WOMPI_EVENTS_SECRET = config("WOMPI_EVENTS_SECRET").strip()

# 🔗 opcional pero recomendado
WOMPI_REDIRECT_URL = config("WOMPI_REDIRECT_URL").strip()
#ngrok
CSRF_TRUSTED_ORIGINS = [
    "https://unstridulating-cloddily-adalberto.ngrok-free.dev",
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True




DEBUG = True

if DEBUG:
    RECAPTCHA_PUBLIC_KEY = "test"
    RECAPTCHA_PRIVATE_KEY = "test"

JAZZMIN_SETTINGS = {

    # =========================
    # 🏷️ IDENTIDAD
    # =========================
    "site_title": "Admin Verde Esmeralda",
    "site_header": "Verde Esmeralda",
    "site_brand": "Panel Administrativo",
    "site_logo": "img/logo200x200.png",
    "login_logo": "img/logo200x200.png",

    "welcome_sign": "Panel de gestión 🌿",
    "copyright": "Verde Esmeralda",

    # =========================
    # 📂 MENÚ ORDENADO (CLAVE)
    # =========================
    "order_with_respect_to": [
        "core",
        "productos",
        "ordenes",
        "usuarios",
        "blog",
    ],

    # =========================
    # 📁 AGRUPACIÓN REAL (PRO)
    # =========================
    "custom_links": {
        "core": [
            {
                "name": "Ver sitio",
                "url": "/",
                "icon": "fas fa-globe",
            },
        ]
    },

    # =========================
    # 🎯 ICONOS
    # =========================
    "icons": {
        "core": "fas fa-leaf",

        "core.Nosotros": "fas fa-seedling",
        "core.Equipo": "fas fa-users",
        "core.ConfiguracionSitio": "fas fa-cogs",
        "core.Contacto": "fas fa-envelope",
        "core.MensajeContacto": "fas fa-inbox",
        "core.Taller": "fas fa-spa",
        "core.Inscripcion": "fas fa-user-check",

        "productos.Producto": "fas fa-box-open",
        "productos.Categoria": "fas fa-tags",

        "ordenes.Pedido": "fas fa-shopping-cart",

        "usuarios.Profile": "fas fa-user",

        "blog.Post": "fas fa-blog",
        "blog.Categoria": "fas fa-folder",
    },

 

    # =========================
    # 🎨 ESTILO PROPIO (CLAVE)
    # =========================
    "custom_css": "css/admin.css",

    # =========================
    # 🧾 FORMULARIOS PRO
    # =========================
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "core.Nosotros": "horizontal_tabs",
        "core.Taller": "horizontal_tabs",
        "core.ConfiguracionSitio": "horizontal_tabs",
    },

    # =========================
    # ❌ DESACTIVADO (IMPORTANTE)
    # =========================
    "show_ui_builder": False,
}