# Generated by Django 6.0.3 on 2026-03-17 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaDeseos', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='producto',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listaDeseos.wishlist')),
            ],
            options={
                'unique_together': {('wishlist', 'producto')},
            },
        ),
    ]
