# Generated by Django 6.0.3 on 2026-03-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('cargo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(upload_to='equipo')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('historia', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='nosotros')),
                ('frase', models.CharField(blank=True, max_length=200)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
