# Generated by Django 6.0.3 on 2026-04-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_taller_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('terminos', 'Términos y condiciones'), ('privacidad', 'Políticas de privacidad')], max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
